### ISSUE TITLE
an error of the docker image

### ISSUE THREAD

**Issue by jingpengw** [supersergiy/znnphi_interface#1]
I am using the same configuration format of gpu kaffe, and get an error.
does the docker image can automatically compile the network, or I should manually do it?

```
/usr/local/lib/python2.7/dist-packages/tifffile/tifffile.py:306: UserWarning: ImportError: N
o module named '_tifffile'. Loading of some compressed images will be very slow. Tifffile.c 
can be obtained at http://www.lfd.uci.edu/~gohlke/                                          
  "ImportError: No module named '_tifffile'. "                                              
Traceback (most recent call last):                                                          
  File "/opt/kaffe/python/forward.py", line 24, in <module>                                 
    net = cfg.net()                                                                         
  File "/opt/kaffe/python/config.py", line 97, in net                                       
    model   = self.get('forward','model')                                                   
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get                               
    raise NoSectionError(section)                                                           
ConfigParser.NoSectionError: No section: 'forward'                                          
catch an error while executing the task: ErrorException("failed process: Process(`python2 /o
pt/kaffe/python/forward.py 0 /tmp/julia7emiql.cfg 1`, ProcessExited(1)) [1]")               
ERROR: LoadError: failed process: Process(`python2 /opt/kaffe/python/forward.py 0 /tmp/julia
7emiql.cfg 1`, ProcessExited(1)) [1]                                                        

```

**Comment by jingpengw** [comment]
it is a config file problem.
